### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by legoboy0215**
IDK... Maybe wrong?

### CODE REVIEW

**Comment by jojoe77777** [comment]
Don't let @PEMapModder see this, @legoboy0215... Unless you want to be shouted at.

**Comment by legoboy0215** [comment]
You did it on purpose. You know mentioning him will notify him... -_-

**Comment by jojoe77777** [comment]
Oops, sorry, got confused. Thought you were adding quotation marks.

**Comment by PEMapModder** [comment]
Why did I get a notification here?

**Comment by jojoe77777** [comment]
Because I mentioned you, sorry peoples.

**Comment by legoboy0215** [comment]
I bet your ass that you did it on purpose :P

**Comment by jojoe77777** [comment]
Well, yeah, it was on purpose, because I misunderstood the commit.

**Comment by PEMapModder** [comment]
@FlamingGenius why you close this though? The pull request is right.

**Comment by CoderJoeW** [comment]
This is different from the current config file

**Comment by ifvictr** [comment]
@FlamingGenius Maybe because the PR corrects your mistakes? :-1:

**Comment by CoderJoeW** [comment]
What?

**Comment by PEMapModder** [comment]
@FlamingGenius what do you mean by different? It is the same as on `FlamingGenius:master`.

**Comment by jojoe77777** [comment]
@PEMapModder This is GitHub...

**Comment by PEMapModder** [comment]
@jojoe77777 edited.

**Pull request closed without merging**
