### PR TITLE
Looks... MUCH BETTER!

### PR DESCRIPTION
**Pull request by legoboy0215**
Optional of course :P

### CODE REVIEW

**Comment by legoboy0215** [comment]
Why?

**Comment by CoderJoeW** [comment]
I have a editor where i put the spaces in as i code and this will just confuse me

**Comment by legoboy0215** [comment]
Oh. But you still had typos. int is not a string.

**Comment by CoderJoeW** [comment]
Nevertheless this code is entirely different from what i have now and ive tested the plugin everything in the code is currently working

**Comment by Gamecrafter** [comment]
@legoboy0215 He wants to make it look like he wrote everything himself. Merging the PR will increase the contributor count. @FlamingGenius Don't think you know everything, you should merge the PRs. They are correct, but what you were doing was wrong.

**Comment by CoderJoeW** [comment]
I have no issue accepting a pr but when i have already added more code accepting would be pointless

**Comment by CoderJoeW** [comment]
Cant merge "nil is not string"

**Comment by legoboy0215** [comment]
What do you mean @Gamecrafter?

**Pull request closed without merging**
